pppd/fsm.c
=> Fix a typo in comment.  Diff from Yuuichi Someya.

pppd/ipcp.c, pppd/options.c, pppd/plugins/pppol2tp/pppol2tp.c
Paul:
I've updated the pull request based on your comments to the previous request.
Thank you,
Nathan
=> Pppd print changes

chat/chat.c, pppd/auth.c, pppd/multilink.c, pppd/plugins/pppol2tp/openl2tp.c, pppd/plugins/radius/avpair.c, pppd/plugins/radius/config.c, pppd/plugins/radius/radius.c, pppd/plugins/radius/radiusclient.h, pppd/plugins/radius/radrealms.c, pppd/plugins/rp-pppoe/Makefile.linux, pppd/plugins/rp-pppoe/if.c, pppd/plugins/rp-pppoe/plugin.c, pppd/plugins/rp-pppoe/pppoe-discovery.c, pppd/plugins/rp-pppoe/pppoe.h, pppd/plugins/winbind.c, pppd/sys-linux.c, pppstats/pppstats.c
=> Various fixes for errors found by Coverity Scan static analysis

pppdump/pppdump.8, pppstats/pppstats.8
In Fedora we did man page scan and identified missing options.
This is an attempt to add them to the manual pages.
=> Added missing options to manual pages.

pppd/pppd.8
Signed-off-by: Craig McQueen <craig@mcqueen.id.au>
=> pppd: Add documentation of stop-bits option to pppd man page

pppd/ipv6cp.c, pppd/ipv6cp.h, pppd/pppd.8
=> Add ipv6cp-accept-remote option

pppd/plugins/passprompt.c
Return code 128 is reserved for the case when a user hits cancel on the
prompt program. We should not ask for the password again.
=> Disable asking password again when prompt program returns 128

pppd/plugins/pppol2tp/Makefile.linux
Maybe $(INSTRUCT) is forgotten.
=> add $(INSTROOT) to $(DESTDIR)

pppd/sys-solaris.c
=> Fix netif_set_mtu for Solaris

pppd/plugins/radius/avpair.c, pppd/plugins/radius/dict.c, pppd/plugins/radius/radiusclient.h
Handling of IPv6 RADIUS dictionary attributes, see issue #89
=> Handle IPv6 RADIUS attributes

pppd/ipcp.c, pppd/main.c, pppd/options.c, pppd/pppd.h
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=101587
=> Add option to specify ip-up script

pppdump/Makefile.linux
=> support building pppdump with the system zlib

pppd/plugins/radius/Makefile.linux, pppdump/Makefile.linux
=> Allow to override the optimization level with CFLAGS

.github/workflows/buildroot.yaml
Here is the first pull request for automated build tests.
It uses latest stable Buildroot (2020.11.1) to build a PPP branch on each repository push.
Currently, the following architectures are built :
* x86
* x86_64
* arm
* aarch64
* ppc64le
* mips32
* mips64
Each architecture is built against glibc, uClibc and musl.
=> Automated build (multiple architectures and C libraries using Buildroot).

pppd/ipv6cp.c, pppd/multilink.c, pppd/pppd.h, pppd/sys-linux.c, pppd/sys-solaris.c
On all places is just needed hardware address for the first ethernet-style
interface. So provide it by new get_first_ether_hwaddr() function.
=> Combine get_first_ethernet() and get_if_hwaddr() into one function

.github/workflows/solaris.yaml, pppd/sys-solaris.c
This is the second pull request for automated build tests.
It builds latest PPP version on Solaris 11.4 using gcc 7.3.0.
=> Solaris automated CI build.

sample/auth-down, sample/auth-up, sample/ip-down, sample/ip-up, sample/options, sample/options.ttyXX, sample/pap-secrets
=> Add some configuration samples

pppd/eap-tls.c
This change allows users to specify "cert" and "key" arguments where the prefix leading up to the ':' indicates the engine e.g. pkcs11, the entire string is passed down to the engine library which does the parsing. In the case of pkcs11.so (OpenSC project's libp11) engine for OpenSSL, it will now correctly parse the PKCS11 URI string (See RFC7512).
=> Allow users to use Engine and ID strings unmodified to the OpenSSL engine

pppd/sys-linux.c
Linux kernel versions prior 3.11 do not support setting IPv6 peer
addresses. On error try fallback to old IOCTL method.
=> pppd: Fix IPv6 compatibility with older kernel versions

README.pppoe
Hi,
Could I get reviews for the following trivial fix, please?
Cheers.
=> README.pppoe: Fix spelling

chat/chat.c, pppd/main.c, pppd/plugins/passprompt.c, pppd/plugins/pppoatm/pppoatm.c, pppd/plugins/pppoe/common.c, pppd/plugins/pppol2tp/pppol2tp.c, pppd/plugins/radius/avpair.c, pppd/plugins/radius/buildreq.c, pppd/plugins/radius/config.c, pppd/plugins/radius/radius.c, pppd/plugins/radius/sendserver.c, pppd/plugins/radius/util.c, pppd/plugins/winbind.c, pppd/sys-linux.c, pppd/tty.c, pppd/utils.c
This is take two of PR#308 breaking each change out in a separate commit to make it easier for the reviewer to figure out what changed. Also incorporating feedback from @pali and @paulusmack. Change fixes compiler warnings on Ubuntu w/GCC and CLang installed.
This closes PR#308 in favor of this new PR
Signed-Off: Eivind Naess <eivnaes@yahoo.com>
=> Fix compiler warnings

.github/workflows/solaris.yaml, .github/workflows/ubuntu.yaml
This ensures installation code to be tested.
=> CI: Perform installation step

pppd/ipcp.c, pppd/ipcp.h, pppd/pppd.8
Signed-off-by: Michael Everitt <gentoo@veremit.xyz>
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>
=> Add option to ask peer for WINS address

configure.ac, pppd/Makefile.am, pppd/auth.c, pppd/eap-tls.c, pppd/eap.c, pppd/ipcp.c, pppd/main.c, pppd/options.c, pppd/pathnames.h, pppd/plugins/pppoe/Makefile.am, pppd/plugins/pppoe/plugin.c, pppd/plugins/radius/Makefile.am, pppd/plugins/radius/pathnames.h, pppd/plugins/radius/sendserver.c, pppd/utils.c
Fix for issue #339
This allows a user to configure the lock directory via configure variables.
=> Ppp autotools

pppd/sys-linux.c
Move common code for sending rtnetlink message into the new
send_rtnetlink_msg() function.
=> pppd: De-duplicate Linux rtnetlink code

pppd/sys-linux.c
Due to workaround in kernel module ppp_generic.ko in function
ppp_nl_newlink(), kernel may return -EBUSY error to prevent possible
mutex deadlock. In this case userspace needs to retry its request.
Proper way would be to fix kernel module to order requests and mutex
locking, so prevent deadlock in kernel and so never return this error to
userspace. Until it happens we need retry code in userspace.
=> pppd: Retry registering interface when on rtnetlink -EBUSY error

chat/chat.c
This improves the way that signals are handled in chat.
First, signal handlers should not be calling functions which are not async-signal-safe; doing so incurs the possibility of deadlock.  Thus we can't call fatal() in signal handlers; instead we set 'fatalsig', which functions both as a flag and as an indication of which signal occurred, and check that at various points (basically after any operation which might block) using the new function checksigs().
Secondly, using sigaction rather than signal() means that we can control whether calls such as read() get restarted after a signal, and whether the signal disposition gets reset when the signal is delivered.  That simplifies sigalrm(); we no longer need to re-register the handler, and we don't need the kludge of setting stdin to …
=> chat: Improve signal handling

pppd/plugins/pppoe/pppoe-discovery.8, pppd/plugins/radius/pppd-radattr.8, pppd/plugins/radius/pppd-radius.8
My legal name and my email address have changed since the files affected by the PR were created; this PR corrects the name and address to their current values.
=> Update DFS's legal name and email address to correct values.

chat/chat.c, pppd/auth.c, pppd/chap_ms.c, pppd/eap.c, pppd/ipv6cp.c, pppd/options.c, pppd/plugins/pppoatm/pppoatm.c, pppd/plugins/pppoe/plugin.c, pppd/plugins/radius/radius.c, pppd/plugins/radius/radrealms.c, pppd/ppp-md4.c
Should address a few of the Coverity issues found in #394 
Also closes #403
=> Plugs a few of the issues uncovered by Coverity

pppd/plugins/radius/clientid.c, pppd/plugins/radius/config.c
This PR fixes this Issue #400. Please approve.
=> add fclose operation to fix file pointer not closed after use

pppd/chap_ms.c, pppd/options.c, pppd/plugins/radius/radius.c
These should be all resolved by the following commits.
=> Additional fixes for various configure options (less frequently used) that broke

configure.ac, pppd/plugins/pppoe/config.h.in, pppd/plugins/radius/config.c
Just adding these suggested fixes as a PR
=> Fixes for #411 and #413

pppd/plugins/radius/radattr.c
=> plugins/radius: fix segfault during shutdown.

pppd/Makefile.am, pppd/crypto.c, pppd/crypto.h, pppd/main.c
This commit adds additional calls to help troubleshoot problems related to crypto.
=> Adding additional functions to handle debugging of crypto calls.
