pppd/options.c
pppd/pppd.8
pppd/sys-linux.c

This allows user to specify the 'metric' (or 'prio') for the default
route set by pppd. This is useful in multi-ISP setups where there
might be more than one default gateway.
Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>

pppd: add support for defaultroute-metric option

---

pppd/plugins/Makefile.linux

The current recursive loops do not check the exit status of make
in subdirs which leads to `make` passing even when a subdir failed
to compile or install.
URL: https://bugs.gentoo.org/334727
Signed-off-by: Martin von Gagern <Martin.vGagern@gmx.net>
Signed-off-by: Mike Frysinger <vapier@gentoo.org>

abort on errors in subdir builds

---

scripts/poff

poff could kill other pppd processes when there are many pppd running on different serial port. For example, if I run "poff ttyUSB1", pppd running on ttyUSB1, ttyUSB10, ttyUSB13, ttyUSB19 could also be killed.
$ ps axw | grep "pppd call"
1415 ttyUSB25 SNs+   0:00 /usr/sbin/pppd call ttyUSB25
3692 pts/4    S+     0:00 grep --colour=auto pppd call
5077 ttyUSB8  SNs+   0:00 /usr/sbin/pppd call ttyUSB8
5348 ttyUSB0  SNs+   0:00 /usr/sbin/pppd call ttyUSB0
9297 ttyUSB16 SNs+   0:00 /usr/sbin/pppd call ttyUSB16
11461 ttyUSB4  SNs+   0:00 /usr/sbin/pppd call ttyUSB4
12625 ?        SNs    0:00 /usr/sbin/pppd call ttyUSB3
13773 ttyUSB22 SNs+   0:00 /usr/sbin/pppd call ttyUSB22
15972 ttyUSB10 SNs+   0:00 /usr/sbin/pppd call ttyUSB10
23029 ttyUSB13 SNs+   0:00 /usr/sbin/pppd call ttyUSB13
24592 …

 scripts: Avoid killing wrong pppd

---

pppd/utils.c

print_string() displays characters as \\%.03o but without first
casting it from "char" to "unsigned char" so it gets sign-extended
to an int. This causes output like \37777777630 instead of \230.
Signed-off-by: Philip A. Prindeville <philipp@redfish-solutions.com>

pppd: Fix sign-extension when displaying bytes in octal

---

pppd/plugins/rp-pppoe/plugin.c

Once the kernel handles PPPoE PADTs correctly[1], a PADT triggered
disconnect will result in EALREADY when pppd tries to clear the session ID.
Simply ignore the error if, and only if, the error is EALREADY
[1] https://patchwork.ozlabs.org/patch/444717/
Signed-off-by: Simon Farnsworth <simon@farnz.org.uk>

Suppress false error message on PPPoE disconnect

---

pppd/plugins/rp-pppoe/plugin.c

Once we've terminated the PPP session, there is no chance of a PPP layer
disconnect. Some PPPoE relays don't detect the PPP session going down, and
depend on a long timeout or a PPPoE PADT to terminate the session.
Send a PADT on disconnect to work around these buggy relays.
Signed-off-by: Simon Farnsworth <simon@farnz.org.uk>

Send PADT on PPPoE disconnect

---

scripts/plog

Executing `plog` when `ppp.log` is not present will not show anything is most cases, because it takes the last few lines of `syslog` before grepping. You have to type `plog -n <some large number>` to actually see something.
This pull request makes plog grep first, so it shows the last few _relevant_ lines. See paulusmack/ppp#42.

plog: count only relevant lines from syslog

---

pppd/plugins/rp-pppoe/pppoe.h

This fixes builds with newer kernels. Basically, <netinet/in.h> needs to be
included before <linux/in.h> otherwise the earlier, unaware of the latter,
tries to redefine symbols and structures. Also, <linux/if_pppox.h> doesn't work
alone anymore, since it pulls the headers in the wrong order, so we better
include <netinet/in.h> early.

pppoe: include netinet/in.h before linux/in.h

---

pppd/sys-linux.c

According to POSIX, the canonical location for errno.h is on the top level.
This fixes a warning that occurs when compiling against musl libc.

Change include from sys/errno.h to errno.h

---

pppd/plugins/rp-pppoe/pppoe-discovery.c

The pppoe-discovery program calls error() from the CHECK_ROOM macro
defined in pppoe.h. Since this standalone program is not linked with the
rest of pppd, the only way this can build is by linking to glibc's
proprietary error(3) function instead of the function of the same name
(but with different arguments) defined in pppd/utils.c.
So when linked with glibc, this probably crashes when the assertion
fails. With musl libc, the binary cannot be built in the first place
because it does not provide the doppelganger.

Define error() to print to stderr

---

pppd/main.c

Yes, this does actually make a difference. :)
There's a new FORTIFY implementation floating about that doesn't like it when some standard library functions are redeclared without a special, compiler-specific attribute. So, when trying to compile ppp with said FORTIFY impl enabled, my compiler complained about this redeclaration.
With it removed, everything works fine.

pppd: Remove unused declaration of ttyname.

---

pppd/Makefile.linux
pppd/auth.c
pppd/options.c
pppd/pppd.8
pppd/pppd.h

This adds an up_sdnotify option so that systemd services of
Type=notify can have pppd send the READY=1 signal to systemd
once a network protocol (typically IP) is up.
To use up_sdnotify, pppd must be compiled with SYSTEMD=y.
Resolves #70

Use systemd's sd_notify with option up_sdnotify

---

pppd/plugins/rp-pppoe/pppoe-discovery.c
pppd/plugins/rp-pppoe/pppoe.h

This PR consist of multiple commits:
1. show real usage information
2. use correct exit code depending on PADO replies
3. add quiet-mode option
4. add options to tune discovery timeout and attempts.
For details please have a look at the single commit messages.

pppoe-discovery: multiple improvements

---

pppd/main.c
pppd/multilink.c

Make pppd use the unit and not the interface name to get the bundle.
pppd was looking for the default interface name (`pppX`) in the
database to retreive the bundle id on which a new link should
attach, and fails if the `ifname` option is used.

pppd: fix `ifname` option in case of multilink

---

pppd/ipv6cp.c
pppd/ipv6cp.h
pppd/pppd.8
pppd/pppd.h
pppd/sys-linux.c
pppd/sys-solaris.c

Which behaves like IPv4's defaultroute.

Add defaultroute6 options

---

pppd/ipv6cp.c
pppd/pathnames.h
pppd/pppd.8

Vyatta based distros (EdgeOS, VyOS, etc.) are using ip-pre-up.d scripts to rename the ppp device to their format.
However the ip-pre-up script is only invoked by IPCP code, but not IPV6CP. Thus the vyatta scripts has no chance to cleanly do this.

Added /etc/ppp/ipv6-pre-up script

---

pppd/options.c

This makes it easier for scripts to parse the output if necessary
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>

pppd: Print version information to stdout instead of stderr

---

pppd/plugins/radius/config.c

Fixed spelling in pppd/plugins/radius/config.c from 'unkown' to 'unknown'.
Signed-off-by: Nigel Kukard <nkukard@lbsd.net>

pppd: Fixed spelling 'unkown' => 'unknown'

---

pppd/plugins/passprompt.c
pppd/plugins/radius/sendserver.c
pppd/plugins/rp-pppoe/discovery.c
pppd/plugins/winbind.c
pppd/pppd.h
pppd/sys-solaris.c
pppd/utils.c

When pppd receives SIGINT or SIGTERM it should handle it and not try to
restart interrupted syscall.
This change fixes problem that pppd cannot be terminated by SIGINT or
SIGTERM signal when pppd plugins are used.

pppd: Handle SIGINT and SIGTERM during interrupted syscalls

---

pppd/chap_ms.c

Windows Server 2019 skip a space when sending a success message.
This commit accepts such a malformed message and continues normally.
Signed-off-by: Yannay Linveh <yannayl@gmail.com>

Accept Malformed Windows Success Message

---

pppd/plugins/rp-pppoe/pppoe-discovery.c

pppoe-discovery's -W option is totally broken. pppoe-discovery currently
expects that Host-Unique attribute equals to its own process pid if set.
This patch fixes parsing received PPPoE PADO packets when -W option is set.
Same implementation is in pppd pppoe plugin.

Fix -W option for pppoe-discovery utility

---

pppd/sys-linux.c

PPP IPV6CP protocol exchanges only IPv6 Interface Identifiers which are
used for generating IPv6 link-local addresses. As on PPP link cannot be
more hosts and IPv6 link-local addresses are designed for addressing a
single link, set route prefix for local and remote IPv6 link-local
addresses to /128 which means single IPv6 address.
This ensures that Linux kernel would not try to route other IPv6 link-local
addresses over PPP link.
Routable IPv6 prefix on PPP link is later configured either by ICMPv6
Router Advertisement packets or manually/statically. Routable local IPv6
address is then assigned by SLAAC, DHCPv6 or manual/static configuration.
So this change has no effect for routable IPv6 address or routable IPv6
prefix.
Note that pppd for IPv4 already sets netmask to 255.255.255.255, one …

Fix setting prefix for IPv6 link-local addresses

---

pppd/ipv6cp.c

Now in year 2020 we should not have disabled IPv6 support by default.
So let both IPv4 and IPv6 enabled by default.

Enable IPv6 by default

---

pppd/auth.c

If a password has been provided as "", CHAP authentication wouldn't
happen. A user providing a username/password, even if blank, should be
expecting authentication to occur with those set.
Added a check for explicit_passwd property, set on finding the password
argument, to allow CHAP authentication with a blank password.
Signed-off-by: Simon Tate <simon.tate@bt.com>

pppd: Fix blank password usage

---

pppd/lcp.c

Function update_link_stats() is doing more than reading number of received
bytes, e.g. it changes state of link_stats_valid.
This change replace update_link_stats() by get_ppp_stats() in
LcpSendEchoRequest() function to avoid any side effects.

pppd: Do not call update_link_stats() for every LcpSendEchoRequest() call

---

pppd/chap-new.c
pppd/pppd.8

If CHAP authentication is required with the peer but this is never
completed (either because the server never sends the challenge or
because the client doesn't receive the outcome) then the client
will wait forever, relying on the server to terminate the connection.
There are options for server side retries but a client side timeout
option is required to prevent the client from getting stuck if the
server won't terminate the connection. This is defaulted to 60 seconds.
----
>  I think it would be better to resend the CHAP-Response packet, instead of just giving up.
The client can't send a `CHAP Response` if it never received a `CHAP Challenge`. The server may not resend this or the retries may also be lost, so the client must timeout in this scenario.
The server may not accept a duplicate …

pppd: Add client CHAP authentication timeout

---

pppd/ipcp.c

When running, for example, both an L2TP/IPsec and a PPTP server on the same machine, it's nice to have them use different names for client interfaces , for example l2tpX and pptpX. It could be done with pre-ip-up scripts, but pppd assumes that interface name is not changed by them.
This is a patch made by Stephen Hemminger back in Vyatta times, but to my knowledge he never sent it to the maintainers. We are still using it in VyOS and it works well for us, but it would be nice if other people could benefit from it too (and we didn't have to maintain a custom version of pppd).
It looks POSIX-compliant to me, but I do admit I've never tested it on systems other than Linux. If there are any compatibility problems with it or other issues, I'm ready to work on them.

Support for interface renaming by pre-up scripts

---

pppd/eap.c
pppd/eap.h

This implements EAP-MSCHAPv2 as specified by
draft-kamath-pppext-eap-mschapv2-02 [1] in server mode (as the client
mode is already proposed by Thomas [2]).
The flow is camparable to MD5-Challenge, with some additional steps for
confirmation:
* Client sends an EAP request
* Server answers with MD5-Challenge
* Client Naks and requests MSCHAPv2
* Server answers with MSCHAPv2-Challenge
* Client answers with MSCHAPv2-Response
* Server answers with MSCHAPv2-{Success/Failure}
* Client possibly confirms MSCHAPv2-{Success/Failure}
I reused as much as possible from pppd/chap-new.c and pppd/chap_ms.c,
but most of the implementation is protected by static functions.
Therefore eap_chapms2_verify_response is an exact copy of
chapms2_verify_response, likewise for eap_chap_verify which is an exact
copy …

pppd: Add support for EAP-MSCHAPv2 in server mode

---

pppd/sys-linux.c

Use if_nameindex() for enumerating network interfaces and choose the first
one with ARPHRD_ETHER ifr_hwaddr.sa_family.

Implement get_first_ethernet() for Linux systems properly

---

pppd/sys-linux.c

This function should return negative value on error.

Fix indicating failure in Linux get_if_hwaddr() function

---

pppd/sys-linux.c

From https://bugs.debian.org/306261
When using the kernel PPPoE driver, pppd never
closes /dev/ppp when the link has come down.
It opens superfluous fds to the device each time it re-opens the
connection, with the unclosed ones falsely reported always ready for
data by select().
This makes pppd eat up 100% CPU time after the first persist because of
the always instantly returning select() on the unclosed fds.
The problem also occurs with the upstream version, but does not occur
when a pty/tty device is used for the ppp connection.

be sure to close /dev/ppp when reconnecting

---

pppd/main.c

From https://bugs.debian.org/284382
When pppd detaches from the parent normally, that is, without nodetach
or updetach set, the linkpidfile is not created even when linkname is
set.
This is because the create_linkpidfile call in detach() is only made
if the linkpidfile is filled in.  However, linkpidfile is never filled
in until create_linkpidfile has been called.
IMHO the call should be made uncondtionally in detach() since
create_linkpidfile does its own check on linkname anyway.
Please note that the version of pppd in woody always wrote the
linkpidfile after detaching.  It did so in main() however.  That
call has now been removed which is why I'm seeing this problem.

make sure that the linkpidfile is always created

---

chat/Makefile.linux
pppd/Makefile.linux
pppd/plugins/radius/Makefile.linux
pppd/plugins/rp-pppoe/Makefile.linux
pppdump/Makefile.linux
pppstats/Makefile.linux

This should be done by the packaging system, to be able to separate out
debugging symbols into separate packages.

Do not strip installed binaries

---

pppd/chap-new.c

Some Windows 9x/ME clients might be erroneously transmitting the MS domain
along the login name. This allows to strip them on the server side.

Add option to strip MS domain name

---

pppd/plugins/pppoatm/pppoatm.c

Removed some debugging messages and generally cleaned up the source.

cosmetic cleanup of the pppoatm plugin

---

pppd/plugins/radius/radius.c

This allows radius plugin to deal with Framed-MTU Radius attribute and to
set MTU on interface.

add support for the Framed-MTU Radius attribute

---

pppd/main.c

From https://bugs.debian.org/341853
There is nothing security-sensitive there.

make _PATH_CONNERRS world readable

---

scripts/secure-card

People would usually just install expect from their distribution

Change path to expect in secure-card example script

---

pppd/options.c
pppd/pppd.8

From https://bugs.debian.org/51880
“
This would make it much easier for me, and cleaner too, to handle
multiple, mutually exclusive, dialout internet service providers.
”

export $CALL_FILE to the link scripts

---

pppd/Makefile.linux

ppp checks header for existence of crypt.h looking it up in /usr/include.
That's incompatible with non-glibcs or a glibc with multiarch headers
(https://bugs.debian.org/798955). This patch replaces the file existence
test with a compile test.
Reviewed-by: Chris Boot <bootc@debian.org>

Use a compile test to detect crypt.h

---

pppd/Makefile.linux

This makes builds non-deterministic, and doesn't work
when building in sysroot environments (such as yocto).
Signed-off-by: Alexander Kanavin <alex.kanavin@gmail.com>

pppd/Makefile.linux: do not check for bpf header presence on the host

---

pppd/ipv6cp.c
pppd/pppd.h
pppd/sys-linux.c
pppd/sys-solaris.c

Now when get_first_ethernet() is implemented for both Linux and Solaris,
implementation of ether_to_eui64() function can use this function
get_first_ethernet() and therefore be system independent.
So change implementation of ether_to_eui64() to use get_first_ethernet()
function and move it from Linux and Solaris files to common ipv6cp.c file
where it is used.

Deduplicate ether_to_eui64() implementation

---

pppd/ipv6cp.c

In case of PPPoE connection, devnam is ethernet interface. So in this case
calculate EUI-64 IPV6CP identifier from the PPPoE ethernet interface
instead from the first ethernet interface in the system.
This would ensure that each PPPoE connection would have unique IPv6 link
local address calculated from the interface MAC address on which is PPPoE
going to be established.
Currently IPv6 link local address is always calculated from the MAC address
of the first ethernet interface and therefore all active PPPoE connections
have by default same (non unique) IPv6 link local address.

Fix ether_to_eui64() to prefer devnam ether interface

---

pppd/ipcp.c
pppd/ipcp.h
pppd/pppd.8
pppd/pppd.h
pppd/sys-linux.c
pppd/sys-solaris.c

Adds an option to pppd to control whether to replace existing default routes
when using the 'defaultroute' option.
If defaultroute and replacedefaultroute are both set, pppd replaces an existing
default route with the new default route. The old default route is restored when
the connection is taken down.

Add replacedefaultroute option

---

pppd/sys-linux.c

On Linux IPv6 peer address cannot be set via SIOCSIFDSTADDR ioctl like it
is for IPv4 peer address. Linux kernel does not support SIOCSIFDSTADDR for
AF_INET6 PPP interfaces.
The only way how to set IPv6 peer address on Linux is via kernel netlink
interface which is just a little bit complicated compared to one ioctl
call.
Linux kernel for a long time automatically adds IPv6 peer address from
interface into route table so it is not needed to explicitly set routing
for remote peer address. pppd already does not do it for kernel versions
newer than 2.1.16. So the same check is used also for IPv6 peer route
address.
Prior this patch ppp interface was configured as:
$ ip -6 address show dev ppp0
2: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 3
inet6 fe80::2/128 …

Fix setting IPv6 peer address

---

pppd/auth.c

This will allow client side plug-ins like for SSTP to run the auth-up-notifier hook to
process the authentication complete step. This will aid in inspection of the mppe keys 
before the network phase is initiated.

Fix for issue #137: Allow auth-up-notifier even if 'noauth' is specified

---

pppd/eap.c

A simple fix for issue #210 
The algorithm selection is currently implemented inline with the currently attempted algorithm. While RFC3748 allows for sending multiple algorithms as a part of the NAK response. Microsoft will terminate the connection when the first suggested algorithm isn't supported. Currently, EAP-TLS will suggest EAP-MSCHAPV2, which will suggest EAP-SRP, which will suggest EAP-CHAPMD5. 

pppd to send nak suggesting eap-mschapv2 when using eap-tls

---

pppd/Makefile.linux

We were seeing reproducibility issues where one host would use the internal
logwtmp wrapper, another would use the one in libutil. The issue was that in
some cases the "\#include" was making it to CC, in others, "#include". The
issue seems to be related to shell escaping.
The root cause looks to be:
http://git.savannah.gnu.org/cgit/make.git/commit/?id=c6966b323811c37acedff05b576b907b06aea5f4
Instead of relying on shell quoting, use make to indirect the variable
and avoid the problem.
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

pppd/Makefile.linux: Fix reproducibility issue with differing make versions

---

configure

It allows e.g. the following:
./configure --cflags='-Wp,-D_FORTIFY_SOURCE=2'

configure: allow commas in the CFLAGS

---

pppd/Makefile.linux
pppd/plugins/pppoatm/Makefile.linux
pppd/plugins/pppoe/Makefile.linux

Is there reason for non standard permissions? In Fedora it's installed
with standard permissions for years.

Install with standard permissions

---

pppd/Makefile.linux

A previous commit to fix a make issue had a copy/paste error, fix it
to refer to the correct header.
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

pppd/Makefile.linux: Fix copy/paste typo

---

pppd/ipcp.c

Respect nosendip option and do not send our IP address to peer even when
peer send to us IPCP ConfNak packet with address 0.0.0.0.
Without this patch pppd sends own local IP address to remote peer and it
can be reproduced with following command:
$ ./pppd/pppd debug local noauth nolock nodetach asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp noipv6 nodefaultroute noipdefault pty "./pppd/pppd debug local noauth nolock nodetach asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp noipv6 nodefaultroute nosendip 10.0.0.1:10.0.0.2 notty"
Without this patch first pppd receives 10.0.0.1 address from second pppd
even second pppd is configured to not send its IP address.
rcvd [LCP ConfReq id=0x1 <magic 0x7cf29fab>]
sent [LCP ConfReq id=0x1 <magic 0x4550b00c>] …

Fix nosendip option

---

pppd/ipcp.c

When noremoteip is set then initial hisaddr (peer address) is zero. So to
handle setting correct peer address after establishing connection it is
needed to change logic around 'wo->hisaddr != 0' condition. wo->hisaddr
needs to be updated from initial zero address to correct peer address.

Fix demand mode with noremoteip option

---

pppd/ipcp.c

If peer address is specified and ipcp-accept-remote is not set then peer
address is enforced.
But there is bug in pppd which allows peer to not use supplied address when
it reply with empty IPCP ConfReq. In this case pppd thinks that peer
accepted its idea of remote/peer address even it is not truth.
This issue can be reproduced by running pppd with arguments:
./pppd debug local noauth nolock nodetach asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp nomagic noipv6 noipdefault :10.1.0.1 pty "./pppd debug local noauth nolock nodetach asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp nomagic noipv6 nosendip nodefaultroute 10.0.0.1:10.0.0.2 notty"
Which means that first pppd force usage of address 10.1.0.1 for peer and
second pppd (peer) wants to use …

Fix enforcing peer IP address

---

pppd/ipcp.c

This fixes special case when both ppp ends are configured to send only IP
address of other side and do not send its own IP address. Such setup is
correct because both ends can exchange its IP addresses and therefore they
have full information, they known both local and remote address.
This issue can be triggered by calling pppd with arguments:
./pppd debug local noauth nolock nodetach asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp nomagic noipv6 noipdefault nosendip :10.0.0.1 pty "./pppd debug local noauth nolock nodetach asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp nomagic noipv6 nosendip nodefaultroute :10.0.0.2 notty"
Without this patch IP addresses are not exchanges at all and pppd fails:
rcvd [LCP ConfReq id=0x1]
sent [LCP ConfReq …

Fix negotiation of IP address when only peer addresses are provided

---

pppd/ipv6cp.c

* ipv6cp: Allow to use demand mode without specifying IPv6 address/identifier
* ipv6cp: Fix clearing previous IPv6 LL address in demand mode
* ipv6cp: Remove demand debug notice

ipv6cp: Fix demand mode for IPv6

---

pppd/ipv6cp.c

There is incorrect logic in ether_to_eui64() function. Persistent id cannot
be found when both sources of persistent id fails, not just one.
This fixes ipv6cp-use-persistent option for non-ethernet PPP connections.
Fixes: 952cfa5acc41ad4ceee160420a188a388bb340cf

ipv6cp: Fix ipv6cp-use-persistent option

---

pppd/ipv6cp.c

Option ipv6cp-use-persistent affects only local interface identifier (local
link-local address). It does not affects remote peer interface identifier
(and remote link-local address) therefore ipv6cp-use-persistent option
should not depend on remote address.

ipv6cp: Fix ipv6cp-use-persistent option when remote address is specified

---

pppd/sys-linux.c

glibc versions prior to 2.24 do not define SOL_NETLINK and linux kernel
versions prior to 4.3 do not define NETLINK_CAP_ACK. So add fallback
definitions for these macros into pppd/sys-linux.c file.
Also extend description why we call SOL_NETLINK/NETLINK_CAP_ACK option.
Fixes: #241

pppd: Fix compilation with older glibc or kernel headers

---

pppd/pppd.8
sample/options

In pppd.8 manpage move defaultroute6 option from FREQUENTLY USED OPTIONS
into OPTIONS and add a warning that this option should not be needed or
used on IPv6 networks. Option defaultroute6 is needed only for broken IPv6
networks. Also add nodefaultroute6 into sample options file.

pppd: defaultroute6 is not frequent option and should not be used

---

pppd/sys-linux.c

* pppd: Fix setting flags of IPv6 peer address
* pppd: Disable Duplicate Address Detection for IPv6 peer address
* pppd: Set local and remote IPv6 addresses by one call
* pppd: Define request and response rtnetlink IPv6 structures

pppd: Fix and cleanup code for setting Linux IPv6 addresses

---

pppd/Makefile.linux
pppd/pppcrypt.h

Clang does not have the --print-sysroot option so the shell
snippet silently fails leading to "-I/usr/include/openssl".
Thankfully systems like Gentoo/portage or Yocto/bitbake enable
sysroot poisoning precisely to catch these kinds of bugs.
There is only one user of this non-standard CFLAG include in
pppcrypt.h, so make it consistent with the rest of the sources
(eg. see eap-tls.[h|c] openssl/* includes) and drop the fragile
sysroot hackery.
Signed-off-by: Adrian Ratiu <adrian.ratiu@collabora.com>

pppd: fix cross-compilation using Clang

---

README.eap-tls
pppd/auth.c
pppd/eap-tls.c
pppd/eap-tls.h
pppd/pppd.h

Closes Issue #250
This feature matches closely what OpenVPN and the network-manager-openvpn plugin does for
certificate verification. It allows the end user to configure the certificate to be
matched by it's common name (entire string), it's subject name, or the suffix of a subject name
the latter is especially useful if you are trying to match against a random server in a RADIUS
pool. Lastly, it also allow you to turn off the certificate matching all together.
tls-verify-method can have the following parameter values:
- none
- subject   - The entire subject, e.g. /CN=some.server.org
- name      - The entie common name, e.g. some.server.org
- suffix    - The latter part of a name, e.g. servers.org
Secondly, it also introduces a new parameter 'tls-verify-key-usage' which permits checking …

EAP-TLS: Verify Subject or CommonName by suffix

---

pppd/chap_ms.c

RFC2548 describes the proper values of the MS-MPPE-Encryption-Policy attribute.
and it can only hold 2 values: 1 (encryption allowed) and 2 (encryption required).
See
https://tools.ietf.org/html/rfc2548, section 2.4.4
The correct comparison should be made with an && and not a ||

Fix for issue #218, a logical error in comparing valid encryption policies

---

README.eap-tls
pppd/eap-tls.c

Make sure the variable has a default value. Also, fixing up the README.eap-tls
documentation for the new options.

Fix for Issue #268 - Avoid SIGSEGV and update documentation

---

pppd/eap-tls.c

Allow building of EAP-TLS code when OPENSSL_NO_ENGINE is set.
Signed-off-by: Jan Just Keijser <jan.just.keijser@gmail.com>

Allow building of EAP-TLS code when OPENSSL_NO_ENGINE is set.

---

pppd/Makefile.linux
pppd/Makefile.sol2
pppd/ccp.c
pppd/chap_ms.c
pppd/chap_ms.h
pppd/eap-tls.c
pppd/eap-tls.h
pppd/mppe.c
pppd/mppe.h
pppd/plugins/radius/radius.c
pppd/plugins/winbind.c

The lengthy part of this fix is to refactor the handling of MPPE keys
by moving it into mppe.c and thus reducing the clutter in chap_ms.c.
It does so by renaming the mppe_set_keys/2 to the corresponding
mppe_set_chapv1/mppe_set_chapv2 versions and updates callers of these
functions.
Having done so, it conveniently allows the name "mppe_set_keys" to be
re-used for this new purpose which will copy the key material up to
it's size and then clear the input parameters (avoids leaving the MPPE
keys on the stack).
Additional functions exported via the MPPE code to allow plugins et al. to
access the MPPE keys, clear the keys, and check if they are set. All
plugins and CCP code has been updated to use this API.
This fixes GitHub Issue #258 

Expose the MPPE keys generated

---

README.eap-tls
pppd/auth.c
pppd/eap-tls.c
pppd/eap-tls.h
pppd/pppd.h

This implements the ability to specify the option 'pkcs12' to allow users to provide a PKCS12 formatted file as user credentials. I've tested the current code using PEM, Encrypted Key with PEM, PKCS12. Still pending verification of PKCS11 tokens.

Allow use of PCKS12 certificates when using EAP-TLS

---

pppd/pppd.8
pppd/sys-linux.c

Most Linux architectures and drivers support arbitrary baud rate BOTHER
values via TCGETS2 and TCSETS2 ioctls in struct termios2.
This patch implements support for BOTHER and struct termios2 which allows
pppd to use any baud rate on Linux systems where architecture and drivers
have support for it.
By default standard values are used.
Support for BOTHER is enabled during compilation when header files have
appropriate definitions of TCGETS2 and TCSETS2 ioctls.
Because there is no glibc support for BOTHER and struct termios2 yet, pppd
defines own BOTHER macro and struct termios2.

pppd: Add support for arbitrary baud rates via BOTHER on Linux

---

pppd/sys-linux.c

After successful call to tcsetattr/TCSAFLUSH it is needed to restore
terminal at the end. So set restore_term variable at correct place. Fixes
issue that fatal() call after tcsetattr/TCSAFLUSH does not restore terminal
settings.

pppd: Set restore_term at correct place

---

pppd/utils.c

'val' is unsigned so condition 'val < 0' is always false
fix it by adding signed long variable.
Signed-off-by: Maks Naumov <maksqwe1@ukr.net>

pppd: fix vslprintf %ld for negative values

---

pppd/ipv6cp.c

Enforcing peer IPv6 interface identifier is broken in the same way as it
was broken for peer IPv4 address prior commit 9fe8923419a9 ("pppd: Fix
enforcing peer IP address").
IPv6 test case:
./pppd noauth asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp nomagic  local nolock nodetach  noip  ipv6 ::2,::1  debug pty "./pppd noauth asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp nomagic  local nolock nodetach  noip  ipv6 ::1:1,::1:2  notty"
Without this patch output from first pppd is:
sent [IPV6CP ConfReq id=0x5 <addr fe80::0000:0000:0000:0002>]
rcvd [IPV6CP ConfReq id=0x5 <addr fe80::0000:0000:0001:0001>]
sent [IPV6CP ConfNak id=0x5 <addr fe80::0000:0000:0000:0001>]
rcvd [IPV6CP ConfNak id=0x5 <addr fe80::0000:0000:0001:0002>]
sent [IPV6CP ConfReq …

ipv6cp: Fix enforcing peer IPv6 interface identifier

---

pppd/ipv6cp.c

These options are completely broken and ignored because pppd reflects these
options in the incorrect struct ipv6cp_allowoptions. Instead pppd expects
that these options are reflected in struct ipv6cp_wantoptions. Same applies
also for IPv4 code where these options are reflected in struct wantoptions.
This issue can be tested and verified by following command:
./pppd noauth asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp nomagic  local nolock nodetach  noip  ipv6 ::2,::1 ipv6cp-accept-local ipv6cp-accept-remote  debug pty "./pppd noauth asyncmap 0 default-asyncmap novj noaccomp nopcomp nodeflate nobsdcomp nomagic  local nolock nodetach  noip  ipv6 ::1:1,::1:2  notty"
First pppd prefer to use IPv6 addresses ::2 and ::1 but accept also any
address suggested by second …

ipv6cp: Fix ipv6cp-accept-local and ipv6cp-accept-remote options

---

pppd/ipv6cp.c

In some cases peer may reject our local IPv6 identifier or may send to us
IPV6CP request without any IPv6 identifier or send empty IPv6 identifier
(asking as to generate some identifier for him).
In these special cases pppd always generated some new random IPv6
identifier and completely ignored the fact that user may already specified
IPv6 link local address (used for IPv6 identifier) either at command line
or in config file.
So properly check pppd options and generate new random IPv6 identifier only
in case user did not supply any IPv6 link local address.
If pppd was configured to not allow random identifiers and peer rejected
our enforced identifiers then pppd connection should be terminated.

ipv6cp: Fix enforcing local and peer non-random IPv6 interface identifiers

---

pppd/plugins/radius/dict.c

This patch adds ipv4addr RADIUS data type compatible with RFC8044.
New dictionaries from RADIUS is using ipv4addr instead of old ipaddr data type. This patch is avoiding modification of RADIUS dictionaries to be compatible with PPP.

Add RFC8044 dictionary compatibility for IPv4 address

---

pppd/plugins/radius/radius.c

It could simply be that the accounting server is temporarily down, and
any good accounting server should be able to recover from missed
start/stop frames.  In particular Acct-Session-Time on the first seen
interim update or even stop frame allows for determining start time.
Signed-off-by: Jaco Kroon <jaco@iewc.co.za>

radius: interim and stop frames should not depend on successful start.

---

.gitignore
pppd/Makefile.am
pppd/chap_ms.c
pppd/utils.c

Sadly, introducing autotools broke chap authentication. This change fixes it such that the workaround for broken internal MD4 works.
Note, the NTPasswordHash function should probably just call MD4() function directly and md4.c should implement that with the workaround. That way, this silliness isn't exposed and copied to other places (if MD4 would be used again, if ever?)

Using OpenSSL for MD4 isn't compatibile how NTPasswordHash is using it.

---

pppd/plugins/pppoe/Makefile.am

Backward compatibility symlink is there already for one ppp release. Remove
it for next ppp release to not conflict with real rp-pppoe.so plugin. So
both ppp's pppoe.so and rp's rp-pppoe.so plugins can be installed together.
Now when conversion to automake was done, it is a good time to drop this
problematic symlink from default installation.

pppoe: Remove rp-pppoe.so symlink to not conflict with real rp-pppoe.so plugin

---

configure.ac

Options that specify --with-logfile-dir, or --with-plugin-dir, or --with-runtime-dir needs to be specified using AC_ARG_WITH, not AC_ARG_ENABLE.
If you try to specify --without-openssl, then the conditions should be tested against = "xyes". There is a case where the option is either blank or is set to "xno" and the former case wasn't properly handled.
Signed-off-by: Eivind Næss <eivnaes@yahoo.com>

Fixing up a few inconsistencies in configure.ac

---

pppd/main.c
pppd/options.c
pppd/pppd.h
pppd/sys-linux.c

MAXIFNAMELEN is currently hardcoded to 32, but maximal size of interface
name on Linux is just 15 + nul-term byte. This limit is already provided by
IFNAMSIZ macro defined in net/if.h header file.
So replace MAXIFNAMELEN usage by IFNAMSIZ to not silently truncate
interface name.
___
pppd: Replace IF_NAMESIZE by IFNAMSIZ for struct ifreq
Macros IF_NAMESIZE and IFNAMSIZ should be defined to the same value, but
struct ifreq uses IFNAMSIZ. So use "correct" macro.

pppd: Remove usage of incorrect constant MAXIFNAMELEN

---

pppd/Makefile.am
pppd/sys-linux.c
pppd/termios_linux.h

Linux architectures have different content of struct termios2 and also
different value of BOTHER macro. So do not declare any struct termios2 nor
BOTHER macro. Current definitions in ppp were applicable only for x86.
Correct definitions for current architecture are only in <asm/termbits.h>
and <asm/ioctls.h> header files. But Linux header file <asm/termbits.h> is
in conflict with glibc header file <termios.h> and only one can be included
in one source unit. Moreover both header files contains struct termios but
with different content. So it is not possible to use glibc tc* functions
with <asm/termbits.h> definitions.
For this reason provide a new include header file "termios_linux.h" which
provides custom implementation of all glibc's termios.h functions via Linux
ioctl() interface with …

pppd: Fix usage of BOTHER ioctl API on Linux

---

configure.ac
pppd/Makefile.am
pppd/auth.c
pppd/eap-tls.c
pppd/eap-tls.h
pppd/eap.c
pppd/eap.h
pppd/mppe.c
pppd/peap.c
pppd/peap.h
pppd/pppd.8
pppd/pppd.h
pppd/tls.c
pppd/tls.h

Using PEAP/MSCHAPv2 is now supported in PPPD with this change.
* Added options to perform CA/CRL checking and certificate validation consistent with what is already been done for EAP-TLS
* Certificate validation is performed similar to EAP-TLS. In addition to checking the certificate chain, users can now set "remotename" and "tls-verify-method" to validate the certificate name
* Validation of certificate purpose and extended key usage is controlled the option "tls-verify-key-usage".
* Support for MPPE key generation via PEAP
* Man page is updated where appropriate for the new options.
* Added unit-tests for the PEAP code in case of crypto or parameters would change in the future.
* Added the PEAP feature to configure scripts. Users can now control the feature by specifying …

PEAP/MSCHAPv2 support in PPPD

---

pppd/plugins/pppol2tp/pppol2tp.c

Without it, l2tp daemon can't launch ppp, cuz undefined symbol ipv6_up_notifier.

pppol2tp.c add '#ifdef INET6' for optional ipv6

---

NEWS
pppd/ipv6cp.c
pppd/main.c
pppd/options.c
pppd/pppd.h

These allow a user to specify the paths to the scripts
usually located at /etc/ppp/ipv6-up and /etc/ppp/ipv6-down,
similarly to the existing ip-up-script and ip-down-script
options
Signed-off-by: Daniel Barlow <dan@telent.net>

add ipv6-{up,down}-script options

---

.github/workflows/solaris.yaml

The Solaris GitHub action is sticking with macOS 10.15 because the new macOS 11 (that now replaces `macos-latest` image) does not contain the needed VirtualBox software. We will migrate the CI to use the latest macOS image when both the GitHub action and the macOS 11 image are ready.
See [actions/virtual-environments#4060](https://github.com/actions/virtual-environments/issues/4060) and [actions/virtual-environments#4010](https://github.com/actions/virtual-environments/pull/4010).

Fix Solaris CI build.

---

pppd/plugins/pppoe/pppoe-discovery.8
pppd/plugins/pppoe/pppoe-discovery.c

On most Linux systems there is no network interface with name eth0.
So rather make -I interface option as mandatory and do not rely on some default hardcoded interface name.
Also there is no sane default interface choice on systems with more interfaces.
Fixes: #219

pppoe-discovery: Do not set eth0 as default interface and valide all cmdline options

---

pppd/ipv6cp.c
pppd/ipv6cp.h
pppd/pppd.8
pppd/sys-linux.c

IPv6 option `ipv6cp-noremote` is same as IPv4 `noremoteip` option.
IPv6 option `ipv6cp-nosend` is same as IPv4 `nosendip` option.
And option `ipv6cp-use-remotenumber` instruct pppd to use IPv6 remote interface identifier from `remotenumber` option. Useful e.g. for PPPoE connections to generate stable and predicable IPv6 remote interface identifier as `remotenumber` is set by pppoe.so plugin to MAC address of remote ethernet peer.

ipv6cp: Add support for new ipv6cp-noremote, ipv6cp-nosend and ipv6cp-use-remotenumber options

---

pppd/main.c
pppd/plugins/radius/etc/dictionary
pppd/plugins/radius/radius.c
pppd/plugins/radius/radiusclient.h
pppd/pppd.h
pppd/sys-linux.c

This extends the ppp stats structures to 64 bit unsigned integers.  Due
to the linux kernel (as far as I could determine) only keeps 32 bit
counters in the ppp driver, attempts to count wrap-arounds in the stats
updates.  An improved solution would be to keep 64-bit counters kernel
side and only revert to this if the kernel don't have 64-bit counters.
It further ensures that if interim updates are used that we update the
stats periodically (every 25 seconds if the interim update is longer
than 30 seconds, so as to handle up to Gbps speeds running at maximum
capacity, I chose 25 seconds simply to be somewhat unlikely to collide
with frequently in terms of timing with the actual interim updates
themselves.  This could be anything <30, so a prime may be preferable
(eg, every 29s) but I don't …

Add Gigawords to radius packets where applicable.

---

pppd/sys-linux.c

These constants are supported by Linux kernel on SPARC architecture.

pppd: Allow to use additional Bnnn constants

---

pppd/eap.c

Need to be able to set the correct length of the username before calling chap/chams make_response.
Signed-off-by: Eivind Næss <eivnaes@yahoo.com>

Need to update the esp->ea_client.ea_namelen variable

---

pppd/eap-tls.c

Fix the following build failure with libressl:
```
eap-tls.c: In function 'ssl_msg_callback':
eap-tls.c:1284:10: error: 'SSL3_RT_HEADER' undeclared (first use in this function); did you mean 'SSL3_RT_ALERT'?
1284 |     case SSL3_RT_HEADER:
|          ^~~~~~~~~~~~~~
|          SSL3_RT_ALERT
```
Fixes:
- http://autobuild.buildroot.org/results/7d721833bddf73531fa03b0a626511af6826d0df
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

pppd/eap-tls.c: fix build with libressl

---

pppd/sys-linux.c

This rearranges the PPP_WITH_IPV6CP guards added in commit
80b8744eb42c ("Changing INET6 to PPP_WITH_IPV6CP and adding configure
option", 2021-08-06) so that we (a) always include the rtnetlink
headers, since we need them for get_ppp_stats_rtnetlink(), and (b)
don't include eui64.h unless we have IPV6 support.
Fixes: 80b8744eb42c ("Changing INET6 to PPP_WITH_IPV6CP and adding configure option")
Signed-off-by: Paul Mackerras <paulus@ozlabs.org>

pppd: Fix compilation on Linux when IPV6 is disabled

---

pppd/sys-linux.c

pppd currently creates ppp network interface via PPPIOCNEWUNIT ioctl API.
This API creates a new ppp network interface named "ppp<unit_id>". If user
supply option "ifname" with custom network name then pppd calls SIOCSIFNAME
ioctl to rename "ppp<unit_id>" to custom name immediately after successful
PPPIOCNEWUNIT ioctl call. If custom name is already registered then
SIOCSIFNAME ioctl fails and pppd close current channel (which destroy also
network interface).
This has side effect that in the first few miliseconds interface has
different name as what user supplied.
Tools like systemd, udev or NetworkManager are trying to query
interface attributes based on interface name immediately when new
network interface is created.
But if interface is renamed immediately after creation then these …

pppd: Add support for registering ppp interface via Linux rtnetlink API

---

.github/workflows/solaris.yaml

GitHub says that macOS 10.15 support will be removed at the end of the month (see https://github.com/actions/virtual-environments/issues/5583), so this update is needed.
~~Sadly, the build time seems to be twice longer...~~ No, it's the same than before.

CI: Updated the Solaris GitHub action to use macOS 12

---

pppd/sys-linux.c

Linux kernel has nasty bug / feature. If PPPIOCNEWUNIT is called with
negative ppp unit id (which is default option when command line argument
"unit" is not specified; and tells kernel to choose some free ppp unit id)
and the lowest unused/free ppp unit id is present in some existing network
interface name prefixed by "ppp" string then this PPPIOCNEWUNIT ioctl
fails. In this case kernel is basically unable to create a new ppp
interface via PPPIOCNEWUNIT ioctl when user does not specify some unused
and non-conflicted unit id.
Linux kernel should be fixed to choose usable ppp unit id when was
requested via PPPIOCNEWUNIT parameter -1.
Until this happen add a workaround for pppd to help choosing some random
ppp unit id when kernel returns this error.
Simple test case (run on system when there …

pppd: Workaround generating of ppp unit id on Linux

---

pppd/sys-linux.c

Response structure is incomplete when returned length is less than required
structure length.
CC: @jkroonza

pppd: Fix check for incomplete ppp_stats nlmsgerr structure

---

pppd/main.c
pppd/options.c
pppd/pppd.h

Fixes issue #251 by introducing a new option to print all supported options.
This also fixes up the show version function to include copyright and package name from autotools. Also supports "-v", a short hand version for --version.
Signed-off-by: Eivind Næss <eivnaes@yahoo.com>

Add option to show all options (show-options)

---

.github/workflows/ubuntu.yaml
configure.ac

1. Use uppercase for `prefix` parameter
`SYSTEMD_CFLAGS` is used elsewhere so `prefix` cannot be lowercase.
https://autotools.info/pkgconfig/pkg_check_modules.html
2. The module name should be `libsystemd`
Previously it will result in the following compile error when building pppd/auth.c:
> /usr/bin/ld: pppd-auth.o: undefined reference to symbol 'sd_notify@@LIBSYSTEMD_209'
> /usr/bin/ld: /usr/lib/libsystemd.so.0: error adding symbols: DSO missing from command line
This is due to missing `-lsystemd-daemon` flag which is provided by `libsystemd-daemon-devel` package on Debian or `systemd-libs` on ArchLinux. And the proper .pc file in the package is `libsystemd` not `systemd`.
https://stackoverflow.com/a/38303241

Fix libsystemd detection

---

pppd/lcp.c

If the lcp-echo-adaptive option is specified, it means that seeing received traffic on the link is considered to be an indication that the link is working.  Hence, this resets the count of missing LCP echo-replies to 0 when traffic is seen.  Without this, occasional echo failures interspersed with link traffic can accumulate and end up causing a disconnection even when the link is working correctly.
Signed-off-by: Paul Mackerras <paulus@ozlabs.org>

pppd: Fix spurious LCP echo failures with lcp-echo-adaptive option

---

pppd/plugins/radius/radius.c

For the purposes of our definition:
User-Request - remote side hanging up.
Admin-Reset - local side hanging up.
Reasoning is that typically radius will be used to authentication dial-in users, so if the pppd gets killed locally, that's not the User (client) requesting hangup, but rather the local administrator (be that a manual kill, or as a result of a CoA/Disconnect).
Signed-off-by: Jaco Kroon <jaco@uls.co.za>

radius: distinguish between User-Request and Admin-Reset.

---

pppd/main.c

This surfaces in discussion of issue #389

Should check name, not ifname in ppp_set_ifname

---

pppd/cbcp.h
pppd/ccp.h
pppd/chap.h
pppd/chap_ms.h
pppd/crypto.h
pppd/crypto_ms.h
pppd/ecp.h
pppd/eui64.h
pppd/fsm.h
pppd/ipcp.h
pppd/ipv6cp.h
pppd/lcp.h
pppd/magic.h
pppd/mppe.h
pppd/multilink.h
pppd/options.h
pppd/pppd.h
pppd/session.h
pppd/upap.h

Closes issue #402
Two commits that does the following: 
- Remove autotools defines wrapping standard header files in pppd/pppd.h, especially stdbool.h
- Adds extern "C" declarations to header files

Removes autotools include guards for stdbool.h and friends

---

configure.ac
pppd/Makefile.am
pppd/auth.c

It allows package maintainers to set the default location for the ca directory.

Fix for issue #405, this adds a --with-system-ca-path to configure script

---

pppd/main.c

Closes issue #407 - You can't reference variables that isn't included in the compile
- Adding #ifdef PPP_WITH_IPV6CP to the get notifier function

Compiling without ipv6cp support fails

---

contrib/pppgetpass/Makefile.am

automake does not seem to include noinst_*_MANS in the dist tarball.

Move pppgetpass.8 to EXTRA_DIST

---

pppd/main.c

Bug: https://bugs.gentoo.org/907311

Ensure there is a '/' between PPP_PATH_VARRUN and the PID filename

---

pppd/plugins/passwordfd.c

When configured to detach from the controlling terminal, pppd closes file descriptors 0, 1, and 2 before the passwd hook is called. If the user passes 0, 1, or 2 to the passwordfd option, pppd will fail to read the password.
To work around this, treat passwordfd as a special option and read the password during option processing, before pppd closes it.
Bug: https://bugs.gentoo.org/209294

passwordfd: read password during option processing

---

pppd/ppp-sha1.c

Fixes build with musl-libc toolchains.

pppd/ppp-sha1.c: use uint32_t instead of u_int32_t

---

pppd/crypto_ms.c

Must have been something I forgot to remove when I was working on this code. After this change, you pppd compiles without openssl as long as you add the following to the configure script: ./configure --disable-peap --disable-eaptls --without-openssl

Fixes issue #429, stray include of an openssl header was removed

---

pppd/options.c

found by Coverity
```
602err:
603    fclose(f);
604    privileged_option = oldpriv;
CID 436193 (#1 of 1): Resource leak (RESOURCE_LEAK)10. overwrite_var: Overwriting option_source in option_source = oldsource leaks the storage that option_source points to.
605    option_source = oldsource;
```

pppd/options.c: fix memory leak or error path

---

pppd/plugins/pppoe/if.c

This change will fix the crash that happens in issue #446 
However, it is worth noting that the device name is typically limited by the struct ifr, and the size of the ifr.ifr_name field (15). It's just that when it is used in context of the sockaddr structure, it's being limited to 14 bytes. The origin of this is the "device name" option which is capped at a really large value. Should probably be set to 14??

Fix for #446, don't crash on too long of a device name

---

pppd/plugins/pppoe/pppoe-discovery.8
pppd/plugins/radius/pppd-radattr.8
pppd/plugins/radius/pppd-radius.8
pppd/pppd.8

From man-pages(7):
Where a real minus character is required (e.g., for numbers such as -1,
for man page cross references such as utf-8(7), or when writing options
that  have a leading dash, such as in ls -l), use the following form in
the man page source:
\-

Escape all minus characters in the man pages

---

pppd/lcp.c
pppd/pppd.8
scripts/lcp_rtt_dump
scripts/lcp_rtt_exporter

This patch adds the lcp-rtt-file configuration option, which instructs pppd to add a timestamp to the data section of each LCP echo request frame and then log their round trip time and any detected packet loss to a circular buffer in that file.
Other programs then can asynchronously read the file and report statistics about the line.
I have also added examples of a simple program which dumps the content of the log file and a Prometheus exporter which can be run as a CGI.
This feature was inspired by a similar one in a commercial PPP implementation, but I have never actually seen that and I do not know how it actually works or it was implemented.
Signed-off-by: Marco d'Itri <md@linux.it>

Implement logging the LCP RTT

---

pppd/Makefile.am
pppd/pathnames.h

lock dir changed on linux from /var/lock to /run/pppd/lock with pppd-2.5.0, which makes pppd fail to start if the distribution does not pre-create the directory.
This reverts it back to /var/lock.
~~In the line of configurability, also make the lock dir configurable through ./configure --with-lock-dir for distributions that prefer /run/pppd/lock, but change the default for linux back to /var/lock~~
~~This commit is bigger than it should be, because the current configure mechanism for PPPD_RUNTIME_DIR and others is inconditional: pathnames.h has #else cases for when the variable is not defined but that is not possible.~~
~~This does not work for lock dir, because on non-linux platform the path is different, and reproducing this logic at configure time is not trivial.~~
~~Instead of the …

Make lock dir configurable

---

pppd/Makefile.am
pppd/pppd-private.h
pppd/tdb.c
pppd/utils.c
pppd/utils_utest.c

PR #435 makes lockdir default go back to /var/lock, but runtime dir still changed from /run to /run/pppd in commit 66a8c74c3f73 ("Let ./configure control the paths for pppd") and is likely to not exist on some distros, in which case the pppdb will not be created.
This is not a big problem but might as well just try to create the directory if it is missing.
Return code of mkdir does not need to be checked as the following open will fail anyway if mkdir failed.
See: #419

try to create rundir before using them

---

pppd/main.c
pppd/pathnames.h
pppd/pppd.8

This no longer differentiates between which sub protocols brings an
interface up or down, merely tracks which sub protocols have brought up
and interface, and which have not yet taken it down.
There is one caveat here, I use pointer comparison on these names, so
the absolutely cannot be anything other than a compile-time constant,
and I'm not sure whether or not at least -O1 is required or not, ie, if
the compiler will eliminate multiple "STRINGS" to a single instance in
memory.
I'm unable to test the solaris code, but I don't see any reason why this
should not work.
Signed-off-by: Jaco Kroon <jaco@uls.co.za>

pppd: implement net-init, net-pre-up and net-down.

---

pppd/sys-linux.c

short them out.
Upstream commit in Linux refers.
commit 10c9ead9f3c6bb24bddc9a96681f7d58e6623966
Author: Roopa Prabhu <roopa@cumulusnetworks.com>
Date:   Wed Apr 20 08:43:43 2016 -0700
rtnetlink: add new RTM_GETSTATS message to dump link stats
This commit adds the #defines and structs used, so simply not compiling this code if the required #defines isn't there should solve the problem.
Closes: #450

pppd: sys-linux - if NETLINK mechanisms isn't available at compile time,

---

m4/ax_check_openssl.m4

When using lld linker, build fails with
ld.lld: error: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/Scrt1.o is incompatible with elf32-i386
ld.lld: error: /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../lib64/crti.o is incompatible with elf32-i386
ld.lld: error: /usr/lib/llvm/16/bin/../../../../lib/clang/16/lib/linux
The fix is to check pkg-config first, and not force manual -L /usr/lib. If pkg-config succeeded, then we don't bother with -L /usr/lib
Our guess is this what the actual intention was based upon the coments
if pkg-config is installed and openssl has installed a .pc file, then use that information and don't search ssldirs
First found on gentoo linux with llvm profile, please check out Bug: section of the commit for more info and a complete build log.
Bug: …

Fix linking error with lld linkers

---

configure.ac

Previous conftest failed with a compiler error
```
if (sizeof ((struct sockaddr_ll))) {
...
}
```
The double parenthesis failed the evaluation of sizeof and thus caused the AC_CHECK_TYPE fail. Replacing with appropriate AC_COMPILE_IFELSE construct.

Fix for failure to detect the presence of sockaddr_ll in linux/if_packet.h

---

.github/workflows/solaris.yaml

Switched to the latest version of the Solaris GitHub Action that now uses Qemu and libvirt on an Ubuntu runner instead of VirtualBox on a macOS runner.

CI: Fixed the Solaris build.

---

pppd/main.c
pppd/plugins/pppoe/pppoe-discovery.c
pppd/pppd.h
pppd/utils.c

Found when trying to do a simple dbglog(__FUNCTION__);

pppd: constify log format strings.

---

m4/ax_check_openssl.m4

Quick and dirty fix to resolve issue in compiling on Solaris fails.
There might be a longer more exhaustive fixed needed here. This is because Solaris 11.4 has two versions of openssl installed. The default one is 
library/security/openssl
library/security/openssl-11
They are both installed (by default I think), and the 1.0.2 version is compiled to use for application with FIPS certification requirements. We should probably link to the newer one openssl-11, but the paths aren't setup correctly for this, e.g. /usr/include/openssl points to /usr/openssl/default/include via symlink by default. 
Users on Solaris 11.4 should be aware that the way to configure this using the openssl-11 libraries would be to pass the correct 
`--with-openssl=/usr/openssl/1.1` to the configure (or autogen.sh) …

Fixing a problem where the detection of openssl failed on solaris

---

pppd/plugins/radius/radius.c

block.
During he refactor in commit 4cb90c1 the key material used to decrypt the second-half of the encrypted block was accidentally updated from:
MD5(radius_secret + crypt[0..15]); to:
MD5(radius_secret + crypt[0..15] + salt)
Which would obviously mismatch.
This also refactors back into what I believe to be a more readable block with lower nesting and more comprehensive error reporting.
Closes: #453

radius: fix the MPPE key decryption for the second-half of the key

---

pppd/lcp.c

To eliminate the warnings, the lcp_rtt_buffer variable no longer points to volatile, and instead accesses are made using 'ring_header' local variables, which do point to volatile, and contain the same address.

pppd: Rework use of volatile in lcp-rtt code to eliminate warnings

---

pppd/plugins/pppoe/plugin.c

Commit 2b4166d02ed0 ("Close discovery socket after session completed", 2020-11-26) arranged for the discovery socket to be closed when the PPPOE session negotiation was complete.  However, the discovery socket is used for sending a PADT message when the connection terminates, and now that doesn't work because the socket has been closed.
To fix this, we reopen the discovery socket in order to send the PADT message.

pppoe: Fix sending of PADT on connection termination

---

pppd/sys-linux.c

For instance, when using a ppp link as backup link, one would want to add a default route on the ppp link, in *addition* to the existing default route.
d0ccb87156c2 ("pppd: Add replacedefaultroute option (#200)") however broke this case: sifdefaultroute was not passing the metric to defaultroute_exists any more. This commit restores this case.
Fixes #357

Restore adding a default route with different metric

---

.github/workflows/solaris.yaml

This avoids loosing time updating the package cache and installing the needed packages.
This also avoids breaking the Solaris build if the Solaris mirrors are temporarily unavailable.

CI: Used a Solaris VM with all needed build tools preinstalled.

---

.github/workflows/buildroot.yaml

This PR adds the support for RISCV-32 and RISCV-64 architectures.
The updated Buildroot version now natively supports PPP version 2.5.

CI: Updated the Buildroot image to support the RISC-V architecture.

---

.github/workflows/solaris.yaml
.github/workflows/ubuntu.yaml

Node.js 16 actions will be deprecated in Spring 2024, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20.

CI: Updated the 'checkout' actions that were using Node.js 16 to Node.js 20.

---

pppd/plugins/pppoe/discovery.c
pppd/plugins/pppoe/plugin.c
pppd/plugins/pppoe/pppoe-discovery.c
pppd/plugins/pppoe/pppoe.h
pppd/pppd.8

Partially revert a previous commit by pali that seemed to be causing problems, and implement some minor improvements to PPPoE.

PPPoE fixes and improvements

---

pppd/plugins/radius/avpair.c

plugins/radius: Avoid buffer-overrun in rc_avpair_tostr for PW_TYPE_DATE

---

pppd/ipcp.c
pppd/main.c

* pppd/ipcp.c: (ipcp_down): fix comment
* pppd/main.c: (reset_link_stats): reset print_link_stats to 1, set start_time even if get_ppp_stats fails.

fix reliability of print_link_stats (with option persist)

---

pppd/ipcp.c
pppd/main.c
pppd/options.c
pppd/pppd-private.h

This option allow a user to specify the path to the script usually located at /etc/ppp/ip-pre-up, similarly to the existing ip-up-script and ip-down-script options.

pppd: Add ip-pre-up-script option

---

pppd/ipcp.c
pppd/pppd.8

This option allows a user to specify that he does not want to create the /etc/ppp/resolv.conf file with the DNS server addresses.

pppd: Add noresolvconf option

---

pppd/auth.c
pppd/main.c
pppd/pppd-private.h

These options allow a user to specify paths to pap-secrets and chap-secrets files.

pppd: Add pap-secrets and chap-secrets options

---

pppd/main.c
pppd/options.c
pppd/pppd-private.h

These options allow a user to specify paths to scripts usually located at /etc/ppp/net-init, /etc/ppp/net-pre-up and /etc/ppp/net-down, similarly to the existing ip-up-script and ip-down-script options.

pppd: Add net-init-script, net-pre-up-script and net-down-script options

---

.github/workflows/solaris.yaml

The total execution decreased by about 20%, sometimes even more.
The best execution time since now has been 2 minutes 52 seconds when the average time with the old VM is about 6 minutes.

ci: Updated the Solaris action to benefit from the faster VM.

---

pppd/crypto.c

fix this:
```
crypto.c: In function 'PPP_crypto_error':
crypto.c:178:11: error: implicit declaration of function 'vsnprintf' [-Wimplicit-function-declaration]
178 |     off = vsnprintf(buf, len, fmt, args);
|           ^~~~~~~~~
crypto.c:41:1: note: include '<stdio.h>' or provide a declaration of 'vsnprintf'
40 | #include "crypto-priv.h"
+++ |+#include <stdio.h>
41 |
crypto.c:178:26: warning: 'vsnprintf' argument 2 type is 'int' where 'long unsigned int' is expected in a call to built-in function declared without prototype [-Wbuiltin-declaration-mismatch]
178 |     off = vsnprintf(buf, len, fmt, args);
|                          ^~~
<built-in>: note: built-in 'vsnprintf' declared here
```

pppd/crypto: fix gcc 14 build

---

pppd/main.c
pppd/utils.c

Add support of format specifiers %lld and %llu to the function vslprintf and use the correct specifiers for printing 64-bit counters.

pppd: Fix printing 64-bit counters

---

pppd/eap-tls.c

Starting with LibreSSL 4.0.0 the `OPENSSL_load_builtin_modules()` function was removed. It is obsolete after automatic library initialization and now an internal API.

pppd: fix build with LibreSSL 4.0.0

---

pppd/crypto.c

The symbol OPENSSL_VERSION_NUMBER is not defined when pppd is compiled without OpenSSL support, so it evaluates to zero. This results in the following linker error:
crypto.c:241: undefined reference to `ERR_free_strings'

pppd: Fix build without OpenSSL

---

.gitattributes

This relates to #519 and addresses the portion where "we can also exclude things like /.github/ from the release".

.gitattributes to exclude .git* files from git-archive.

---

pppd/auth.c
pppd/main.c
pppd/pppd.8

This PR will cover cases where connection must be reestablished as fast as possible to descrease network downtime:
- connect time expired (ex: connection time limit for billing purposes or dynamic IP change)
- user request (ex: ISP peer shutting down and we must reconnect to another available in pool)
- connection lost (ex: we got cable disconnection or packet loss for a few seconds)

disable holdoff for reconnect on timeout or link failure

---

configure.ac

Since our only PEAP mechanism is MS-CHAP v2, the compile fails if we enable PEAP without MS extensions.  Therefore, for now make PEAP depend on MS extensions, so if MS extensions are disabled, PEAP is automatically disabled.

configure: Make PEAP depend on microsoft extensions

---

pppd/pppd.8

Warning picked up by Debian's lintian:
```
W: ppp: groff-message troff:<standard input>:694: warning: expected numeric expression, got 'r' [usr/share/man/man8/pppd.8.gz:1]
```

pppd.8: fix groff warning

---

pppdump/pppdump.c

GCC 15 defaults to C23 which does not allow K&R declarations.
Credit Yaakov Selkowitz in:
https://src.fedoraproject.org/rpms/ppp/pull-request/12

Fixed building with GCC 15

---

pppd/plugins/pppol2tp/pppol2tp.c
pppd/sys-linux.c

Given a system with the following:
- linux 4.4.302
- kernel headers 3.4.104
- gcc 4.7.3
- binutils 2.22
- glibc 2.18
Compiling ppp fails with the following errors:
```
x86_64-linux-gnu-gcc -std=gnu11 -DHAVE_CONFIG_H -I. -I../pppd/plugins/pppoe  -DSYSCONFDIR=\"/usr/etc\" -DPPPD_RUNTIME_DIR='"/usr/var/run/pppd"' -DPPPD_LOGFILE_DIR='"/usr/var/log/ppp"' -DSYSTEM_CA_PATH='"/usr/etc/ssl/certs"'   -DPPPD_PLUGIN_DIR='"/usr/lib/pppd/2.5.2"'       -O2 -m64 -fPIC -MT pppd-sys-linux.o -MD -MP -MF .deps/pppd-sys-linux.Tpo -c -o pppd-sys-linux.o `test -f 'sys-linux.c' || echo './'`sys-linux.c
In file included from sys-linux.c:125:0:
/usr/include/linux/ppp-ioctl.h:55:14: error: field 'mode' has incomplete type
make[3]: *** [Makefile:1334: pppd-sys-linux.o] Error 1
make[3]: Leaving directory …
```

Move inclusion of <linux/ppp_ioctl.h> to allow geriatric systems to build ppp.

---

pppd/lcp.c

It's possible for `ring_header[2]` to be modified by another process when reading it twice through a volatile pointer, causing it to change from a small value (which doesn't need to wrap around) to a large value which would exceed the size of the buffer.

pppd: Fix potential buffer overflow in lcp_rtt_update_buffer()

---

pppd/session.c

Fixed building with GCC 15 which defaults to C23
and find conflicting declration of getspnam() here with the one provided by shadow.h (extern struct spwd *getspnam (const char *__name);)
Fixes
../../ppp-2.5.2/pppd/session.c: In function 'session_start': ../../ppp-2.5.2/pppd/session.c:185:18: error: conflicting types for 'getspnam'; have 'struct spwd *(void)'
185 |     struct spwd *getspnam();
|                  ^~~~~~~~

pppd/session: Fixed building with GCC 15

---

configure.ac
pppd/Makefile.am
pppd/event-handler.c
pppd/main.c
pppd/plugins/Makefile.am
pppd/plugins/dhcpv6relay/Makefile.am
pppd/plugins/dhcpv6relay/dhcpv6relay.c
pppd/plugins/dhcpv6relay/dhcpv6relay.h
pppd/pppd-private.h
pppd/pppd.h
pppd/sys-linux.c
pppd/sys-solaris.c

After the plugin is loaded, it just needs dhcpv6relay-server option to know where to relay to.
Server will (current planning) need to support option 135 which tells it to which port to send return responses (it will still send from port 547 typically).

dhcpv6relay plugin.

---

pppd/options.c

This reverts commit 26d1b60f4984fe71005c4f1a99691e714920f33c.
Additionally a comment is added so anyone looking at Coverity output will not be tempted to "fix" it again.
Closes: #560

Revert "pppd/options.c: fix memory leak on error path (#441)"

---

pppd/main.c
pppd/options.c
pppd/pppd-private.h
pppd/pppd.8
pppd/sys-linux.c

Hello,
This PR introduces vrf support to pppd and will resolve https://github.com/ppp-project/ppp/issues/311
Tested on Ubuntu 24.04, using accel-pppd for the ppp server:
Setup:
```sh
sudo ip link add sessions type vrf table 1234
sudo ip link set sessions up
```
Client config:
```
plugin pppoe.so
nic-veth1
ifname PPPOE
vrf sessions
user "testuser"
noauth
defaultroute
usepeerdns
```
Start PPPoE session:
```sh
sudo pppd call test debug dump nodetach
```
Check that the ppp interface belongs to the vrf 'sessions':
```sh
ip link show PPPOE 
```
```
128: PPPOE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel master sessions state UNKNOWN mode DEFAULT group default qlen 3
link/ppp
```
^^^ The ppp interface belongs to the vrf sessions (master sessions)
Check that the routes …

pppd: add VRF binding support
